// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okqyaxnjozcsnlnqwuvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rcXlheG5qb3pjc25sbnF3dXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU2ODIsImV4cCI6MjA2NDM4MTY4Mn0.WmQNDYemyazg9xuZsfaai3lt-0DLazXIFdE94nJzo-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);